name: Auto Label
on:
  project_card:
    types: [moved]
jobs:
  update-labels:
    runs-on: ubuntu-latest
    steps:
    - name: Updating labels
      id: addlabeltopr
      uses: Matticusau/projectcard-autolabel@v1.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        autolabel-config: '[{"column":"Draft not updated", "add_labels":["Not updated"]},{"column":"Draft to review", "add_labels":[], "remove_labels":[]}]'
        projectfilter-config: '{"include":["*"], "exclude":[]}'