name: Auto Label
on:
  project_card:
    types: [moved]
jobs:
  update-labels:
    runs-on: ubuntu-latest
    steps:
    - name: Updating labels
      id: addlabeltopr
      uses: Matticusau/projectcard-autolabel@v1.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        autolabel-config: '[{"column":"Next to merge", "add_labels":["NEXT_TO_MERGE"], "remove_labels":[]},{"column":"Merged", "add_labels":[], "remove_labels":["NEXT_TO_MERGE"]}]'
        projectfilter-config: '{"include":["*"], "exclude":[]}' 