name: Move card

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]
  project_card:
    types: [edited]
 
jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Move to In Progress
        uses: bishalrai96/Project_Card_Automation@master
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          label: "QA Passed"
          column: "QA Passed"
          remove-label: "test, review, ready"
