name: Auto labels by Rawl
on:
  pull_request:
    types: [labeled]
jobs:
  update-message:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'NEXT_TO_MERGE' }}
    steps:
      - uses: jenschelkopf/issue-label-notification-action@1.3
        with:
          recipients: |
            NEXT_TO_MERGE=@rawlmp
