name: Log project release
on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:
   
jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_latest_release
        with:
          query: |
            query { 
              repository(owner: "rawlmp", name: "code-review") {
                pullRequests(last:100, states: OPEN){
                  nodes{
                    updatedAt
                    projectCards {
                      edges {
                        node {
                          id
                          project{
                            id
                            name
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          owner: ${{ github.event.repository.owner.name }}
          repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo 'latest release: ${{ steps.get_latest_release.outputs.data }}'"