name: Move PR to column if not updated
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
    
jobs:
  move-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Move PR to column if not updated
        uses: actions/github-script@v4
        with:
          script: |
            const { data: pullRequest } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              sort: 'updated',
              direction: 'desc',
              per_page: 100
            });
            console.log(pullRequest)
            const timeSinceUpdate = new Date() - new Date(pullRequest.updated_at);
            const twelveHoursInMs = 60 * 1000;
            const { data: columns } = await github.projects.listColumns({
              project_id: pullRequest.head.repo.project_id
            });
            const columnName = "Draft not updated";
            const column = columns.find((column) => column.name === columnName);
            if (timeSinceUpdate > twelveHoursInMs && column) {
              await github.projects.moveCard({
                card_id: pullRequest.head.repo_card.id,
                position: "top",
                column_id: column.id
              });
            }
