name: Move PR to column if not updated
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
    
jobs:
  move-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Move PR to column if not updated
        uses: actions/github-script@v4
        with:
          script: |
            console.log(context)

            const updatePR = async (pr) => {
              const { data: columns } = await github.projects.listColumns({
                project_id: 3
              });
              const columnName = "Draft not updated";
              const column = columns.find((column) => column.name === columnName);
              if (timeSinceUpdate > twoMins && column) {
                await github.projects.moveCard({
                  card_id: pr.head.repo_card.id,
                  position: "top",
                  column_id: column.id
                });
              }
            }
            
            const { data: prs } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              sort: 'updated',
              direction: 'desc',
              per_page: 100
            });

            prs.forEach(pr => {
              const timeSinceUpdate = new Date() - new Date(pullRequest.updated_at);
              const twoMins = 2 * 60 * 1000;
              updatePR(pr);
            })
