name: Auto Label
on:
  pull_request:
    types: [labeled]
jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.GA_LABELER }}"
        project-url: "https://github.com/rawlmp/stremio-add-on/projects/1"
        column-name: "QA Passed"
        label-name: "QA Passed"
        columns-to-ignore: "In Review,Ready to deploy,Done"
