name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          stale-pr-message: 'Stale pull request message'
          exempt-issue-labels: 'awaiting-approval,work-in-progress'
          stale-pr-label: 'Not Updated'
          days-before-stale: 1