name: 'Label not updated PRs'
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          stale-pr-message: "This PR hasn't logged any activity for a long time"
          exempt-issue-labels: 'Do not merge'
          stale-pr-label: 'No activity'
          days-before-stale: 0.625 # 15 hours without updates
          include-only-assigned: true
          ignore-pr-updates: true